server:
  port: 9003

eureka:
  client:
    service-url:
      default-zone=http: //localhost:8761
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: note-service
          uri: lb://note-service
          predicates:
            - Path=/contact/**